### ISSUE TITLE
Post-size

### ISSUE THREAD

**Issue by djw4** [andreborud/penguin-theme-dark#1]
Hi Andre, this theme is great thank you very much. Is it possible to adjust the height of the posts on the home? I prefer to list my posts without a picture so it looks a little odd with such a large box of empty space.

If you can let me know what variable to change to make the boxes approximately 50% of their current height I'd really appreciate it.

**Comment by djw4** [comment]
Fixed with using 'code injection' menu in the backend:

```css
<style>main#posts article { flex-basis: calc(33% - 12px) !important; }</style>
```
